### ISSUE TITLE
Data split for the PanNuke dataset ?

### ISSUE THREAD

**Issue by windygoo** [Lewislou/SENUCLS#3]

**Comment by Lewislou** [comment]
Please read this official dataset webpage carefully: https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke

**Comment by windygoo** [comment]
> Please read this official dataset webpage carefully: https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke

With the official three-fold evaluation protocol, the average cls-F1 of Hover-net is 0.504 while the det-F1 is 0.80, as evidenced in Tab.5  in paper "PanNuke Dataset Extension, Insights and Baselines". These results seem to be inconsistent with the baseline performance of Hover-net in your paper (det-F1 0.748 and cls-F1 0.604). So I am wandering if the data split is different.

**Comment by windygoo** [comment]
> Please read this official dataset webpage carefully: https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke

Can I add your wechat for further communication ?

**Comment by Lewislou** [comment]
> Can I add your wechat for further communication ?

Sure, send me an email (weilou@link.cuhk.edu.cn).
